### ISSUE TITLE
Question: Url to Server Interface?

### ISSUE THREAD

**Issue by matlion** [CoreMedia/coremedia-headless-server#1]
Which is the Url to the server interface, which is shown here:
https://minds.coremedia.com/2017/11/09/content-as-a-service/

http://localhost:8080/caas/v1/???

**Comment by matlion** [comment]
This is the URL to the api doc overview:
http://localhost:8080/swagger-ui.html

**Comment by katherine-thompson** [comment]
Hi, thanks for your interest in the headless server! 
Have you answered the question yourself in the second comment? If not, maybe I haven't understood the question...

**Comment by matlion** [comment]
I've answered the question myself :-)
