### ISSUE TITLE
Unsure to which CM versions this is compatible

### ISSUE THREAD

**Issue by Paratron** [CoreMedia/coremedia-headless-server#12]
Currently, there are several badges that this repository has been tested against version 9.x but I was unable to find any information about with which CM versions this project is compatible.

**Comment by amoehlma** [comment]
Have a look at the Releases tab in Github. We write within the release notes which version of the CoreMedia platform is supported. 
As our CMS and LiveContext products are all based on the same platform, it'll work as long as the underlying platform version fits.
 
Please note that the Labs releases may not be updated with every CoreMedia platform release, but the source is available for free, so everyone can make the necessary changes.
